[NES]
name = "Entertainment System"
producer = "Nintendo"
image = "https://upload.wikimedia.org/wikipedia/commons/8/82/NES-Console-Set.jpg"
folders = ["NES"]
extensions = ["nes", "zip", "7z"]

[SNES]
name = "SNES"
producer = "Nintendo"
image = "https://upload.wikimedia.org/wikipedia/commons/3/31/SNES-Mod1-Console-Set.jpg"
folders = ["SNES"]
extensions = ["snes", "sfc", "zip", "7z"]

[GB]
name = "Game Boy"
producer = "Nintendo"
image = "https://upload.wikimedia.org/wikipedia/commons/f/f4/Game-Boy-FL.jpg"
folders = ["GB"]
extensions = ["gb", "zip", "7z"]

[GBC]
name = "Game Boy Color"
producer = "Nintendo"
image = "https://upload.wikimedia.org/wikipedia/commons/7/76/Nintendo-Game-Boy-Color-FL.jpg"
folders = ["GBC"]
extensions = ["gbc", "zip", "7z"]

[GBA]
name = "Game Boy Advance"
producer = "Nintendo"
image = "https://upload.wikimedia.org/wikipedia/commons/7/7d/Nintendo-Game-Boy-Advance-Purple-FL.jpg"
folders = ["GBA"]
extensions = ["gba", "zip", "7z"]

[PSP]
name = "PlayStation Portable"
producer = "Sony"
image = "https://upload.wikimedia.org/wikipedia/commons/4/46/Psp-1000.jpg"
folders = ["PSP"]
extensions = ["iso", "cso"]

[NDS]
name = "DS"
producer = "Nintendo"
image = "https://upload.wikimedia.org/wikipedia/commons/a/a0/Nintendo-DS-Lite-Black-Open.jpg"
folders = ["NDS"]
extensions = ["nds", "zip"]

